=== ha1den1/uzduotis/student.dtd
<!ELEMENT student (id, firstName, lastName, code, account?, subjects?)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT account (id, username, password)>
<!ELEMENT subjects (subject*)>
<!ELEMENT subject (id, name, credits)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT credits (#PCDATA)>
<!ATTLIST id xmlns CDATA #IMPLIED>
<!ATTLIST account xmlns CDATA #IMPLIED>
<!ATTLIST subjects xmlns CDATA #IMPLIED>
<!ATTLIST subject xmlns CDATA #IMPLIED>

=== ha1den1/uzduotis/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student SYSTEM "student.dtd">
<student>
    <id>1</id>
    <firstName>John</firstName>
    <lastName>Doe</lastName>
    <code>JD001</code>
    <account>
        <id>0</id>
        </username>
    <password>password</password>
        <username>johndoe</username>
    </password>
</account>
    <subjects>
        <subject>
            <id>0</id>
            <name>Math</name>
            <credits>5</credits>
        </subject>
        <subject>
            <id>0</id>
            <name>Science</name>
            <credits>4</credits>
        </subject>
    </subjects>
</student>
